/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.catneye;

import java.time.LocalDateTime;
import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.ListCell;
import javafx.scene.control.ListView;
import javafx.stage.Stage;
import javafx.util.Callback;

public class App extends Application {

    public static void main(String[] args) {
        Application.launch(args);
    }

    @Override
    public void start(Stage stage) throws Exception {
        //Parent root = FXMLLoader.load(getClass().getResource("main.fxml"));

        FXMLLoader loader = new FXMLLoader();
        loader.setLocation(getClass().getResource("/main.fxml"));
        Parent root = loader.load();

        Scene scene = new Scene(root, 500, 300);
        stage.setTitle("FXML Welcome");
        stage.setScene(scene);
               
        stage.show();
        
        
        ObservableList<ListObject> objList = FXCollections.observableArrayList();
        objList.add(new ListObject(1, "First","aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", LocalDateTime.now()));
        objList.add(new ListObject(2, "Second", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", LocalDateTime.now()));
        objList.add(new ListObject(3, "Third","ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc", LocalDateTime.now()));
        
        ListView itemsList = (ListView) scene.lookup("#itemsList");
        itemsList.setItems(objList);
        itemsList.setCellFactory(new Callback<ListView<ListObject>, ListCell<ListObject>>() {

            @Override
            public ListCell<ListObject> call(ListView<ListObject> param) {
                ListCell<ListObject> cell = new ListCell<ListObject>() {

                    @Override
                    protected void updateItem(ListObject item, boolean empty) {
                        super.updateItem(item, empty);
                        if (item != null) {
                            setText(item.getLabel());
                        } else {
                            setText("");
                        }
                    }
                };
                return cell;
            }
        });
    }
}
